
  
on:
  schedule:
    # Uruchamianie co 6 godzin
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build: # Nazwa zadania (job)
    runs-on: ubuntu-latest # Typ środowiska, na którym będzie uruchamiane

    steps: # Kroki w ramach tego zadania
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
